2.1 : 2.1.cc
	g++ 2.1.cc -lGL -lglut -lGLEW -o 2.1
2.2 : 2.2.cc
	g++ 2.2.cc -lGL -lglut -lGLEW -o 2.2
2.3 : 2.3.cc
	g++ 2.3.cc -lGL -lglut -lGLEW -o 2.3
2.4 : 2.4.cc
	g++ 2.4.cc -lGL -lglut -lGLEW -o 2.4
3.2 : 3.2.cc
	g++ 3.2.cc -lGL -lglut -lGLEW -o 3.2
